### ISSUE TITLE
Issue with spikejsonrpc.py - TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by gabslx** [sanjayseshan/spikeprime-vscode#29]
I encountered an issue while using the spikejsonrpc.py script for interacting with the Spike Prime hub. When attempting to upload a program using the following command:

**python C:\spiketools\spikejsonrpc.py -t COM17 upload "c:\Users\Desktop\lego\levov2\teste.py" 1**

I received the following error message:
Traceback (most recent call last):
  **File "C:\spiketools\spikejsonrpc.py", line 226, in <module>
    args.func()
  File "C:\spiketools\spikejsonrpc.py", line 154, in handle_upload
    start = rpc.start_write_program(name, size, args.to_slot, now, now)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\spiketools\spikejsonrpc.py", line 80, in start_write_program
    return self.send_message('start_write_program', {'slotid':slot, 'size': size, 'meta': meta})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\spiketools\spikejsonrpc.py", line 55, in send_message
    return self.recv_response(id)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\spiketools\spikejsonrpc.py", line 60, in recv_response
    if 'i' in m and m['i'] == id:
       ^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable**

I have confirmed that the Spike Prime hub is properly connected to my computer through COM17, and I am using the correct version of the script. I have also checked that the file teste.py exists in the specified location. However, the error persists.

Any assistance or suggestions on how to resolve this issue would be greatly appreciated.

**Comment by C-PLUS-PLUSandPYTHON** [comment]
I have the same issue. Hope that he will review this and help us

**Comment by t-j-strey** [comment]
I also have the same issue.  I have performed the same verification steps as shown in OPs issue submission.

**Comment by C-PLUS-PLUSandPYTHON** [comment]
Hi t-j-Strey I think this Extension just doesn’t receive any updates so it’s outdated (last commit 6 years ago)
